wordpress:
  image: tutum/wordpress-stackable
  hostname: kartoza.com
  links: 
   - db
  ports:
   - "2080:80"
  environment:
    DB_NAME: wordpress
    DB_USER: admin
    # TODO - use an env var rather
    DB_PASS: "baz00ka"
    DB_HOST: db
    DB_PORT: 3306
  volumes_from: 
    # so we can have /backups folder for making backups
    - db
  volumes:
    # This so we can share the app dir as a container storage volume
    - /app
    # so we can persist media
    - wp-content/wp-content:/app/wp-content

db:
  hostname: db.kartoza.com
  image: tutum/mysql:5.5
  environment:
    # TODO - use an env var rather
    MYSQL_PASS: "baz00ka"
  volumes:
    - backups:/backups
