## Base compose configuration

wordpress:
  image: tutum/wordpress-stackable
  hostname: inasafe.org
  links: 
   - db
   - sftpmediabackup:sftpmediabackup
   - sftpdbbackup:sftpdbbackup
  ports:
   - "8101:80"
  environment:
    DB_NAME: wordpress
    DB_USER: admin
    # Environment variables with only a key are resolved to their 
    # values on the machine Compose is running on.
    # so make sure to set the DB_PASS env var before using this config file
    # DB_PASS:
    DB_HOST: db
    DB_PORT: 3306
  env_file:
    # Wordpress credentials, set the DB_PASS environment
    - wordpress_credential.env
  volumes_from: 
    # so we can have /backups folder for making backups
    - db
  volumes:
    # This so we can share the app dir as a container storage volume
    - /app
    # so we can persist media
    - ./wp-content:/app/wp-content

sftpdbbackup: &sftpdbbackup
  image: kartoza/sftp-backup:1.0
  hostname: sftpdbbackup
  volumes:
    # this folder is used to store local backups from pg dbbackup
    - ./sftp_backup/backups/db:/backups
    # this folder is used as target folder/source where the backup comes from
    # this backup comes from dbbackup
    - ./sftp_backup/target/db:/db_backup
  environment:
    - DUMPPREFIX=DB_inasafe.org
    - DAILY=14
    - MONTHLY=12
    - YEARLY=3
    # set this to the target/source folder where the backup comes from
    - TARGET_FOLDER=/db_backup
    # You can specify this in sftp_db_credential.env
    # - SFTP_DIR=/inasafe/inasafe.org/db/
  env_file:
    - sftp_db_credential.env

sftpmediabackup: &sftpmediabackup
  image: kartoza/sftp-backup:1.0
  hostname: sftpmediabackup
  volumes:
    # this folder is used to store local backups from django media
    - ./sftp_backup/backups/media:/backups
    # this folder is used as target folder/source where the backup comes from
    # this backup comes from django media
    - ./wp-content:/media_backup
  environment:
    - DUMPPREFIX=MEDIA_inasafe.org
    # reduce frequency because the dump is really big
    - DAILY=3
    - MONTHLY=2
    - YEARLY=1
    - TARGET_FOLDER=/media_backup
    # You can specify this in sftp_media_credential.env
    # - SFTP_DIR=/inasafe/inasafe.org/media/
  env_file:
    - sftp_media_credential.env

db:
  hostname: db.inasafe.org
  build: docker-db
  links:
    - sftpdbbackup:sftpdbbackup
  env_file:
    # Make sure to set the MYSQL_PASS env var before using this config file
    # set MYSQL_PASS environment
    - mysql_credential.env
  volumes:
    - ./backups:/backups
    - ./sftp_backup/target/db:/target
    # This will not work on OSX/Win - comment out for those oses
    # See https://github.com/tutumcloud/tutum-docker-mariadb/issues/5
    # The linux configuration will override this for production mode
    # - ./db:/var/lib/mysql
